services:
  tor:
    build: ./tor
    restart: always
    volumes:
      - ./tor/tor_data:/var/lib/tor
      - ./tor/torrc:/etc/tor/torrc
    ports:
      - 80:80
      - 443:443

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./html:/var/www/html:ro
    depends_on:
      - tor
    network_mode: service:tor

  certbot:
    image: certbot/certbot:latest
    restart: always
    volumes:
      - /var/www/certbot/:/var/www/certbot/:rw
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
