services:
  tor:
    build: ./tor
    restart: always
    volumes:
      - ./tor/tor_data:/var/lib/tor
      - ./tor/torrc:/etc/tor/torrc
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
      - 8080:8080 # NOSTR
      - 3001:3001 # UPTIME_KUMA

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./html:/var/www/html:ro
    depends_on:
      - tor
    network_mode: service:tor

  certbot:
    image: certbot/certbot:latest
    restart: always
    volumes:
      - /var/www/certbot/:/var/www/certbot/:rw
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - tor
    network_mode: service:tor

  nostr:
    image: koalasat/satstralia-web-nostr:0.6
    restart: always
    volumes:
      - ./strfry/onion_urls.txt:/app/onion_urls.txt:ro
      - ./strfry/config/strfry.conf:/etc/strfry.conf:ro
      - ./strfry/db:/app/strfry-db:rw
    depends_on:
      - tor
    network_mode: service:tor

  uptime_kuma:
    image: louislam/uptime-kuma:latest
    restart: always
    volumes:
      - ./uptimekuma/data:/app/data:rw
    depends_on:
      - tor
    network_mode: service:tor
