# Redirect HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name learn.thebiglake.org;

    location /.well-known/acme-challenge {
        root /var/www/certbot;
    }

    return 301 https://$host$request_uri;  # Redirect all HTTP requests to HTTPS
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name learn.thebiglake.org;

    ssl_certificate /etc/letsencrypt/live/learn.thebiglake.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/learn.thebiglake.org/privkey.pem;

    location / {
        proxy_pass http://pages:4000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
    }
}